version: '3.9'

services:
  backend:
    container_name: footabll-games-mvc
    image: maxshen01/football-games-mvc:0.0.1.RELEASE
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    networks:
      - football-games-network
  database:
    container_name: football-games-db
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/footballGames.sql:/docker-entrypoint-initdb.d/footballGames.sql
    networks:
      - football-games-network

networks:
  football-games-network: