version: '3.9'

services:
  frontend:
    container_name: football-tracker-frontend
    image: maxshen01/football-tracker-frontend:0.0.1.RELEASE
    ports:
      - "3000:80"
    networks:
      - football-tracker-network
    depends_on:
      - backend
  backend:
    container_name: football-tracker-mvc
    image: maxshen01/football-tracker-mvc:0.0.1.RELEASE
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    networks:
      - football-tracker-network
  database:
    container_name: football-tracker-db
    image: maxshen01/football-tracker-db:0.0.1.RELEASE
    env_file:
      - .env
    ports:
      - "5432:5432"
    # volumes:
    #   - ./db/footballGames.sql:/docker-entrypoint-initdb.d/footballGames.sql
    networks:
      - football-tracker-network

networks:
  football-tracker-network: